/*PROJECT Q1 FIND total quantity and no of transactions/payment method */
select distinct payment_method,count(*) as no_transaction,
SUM(quantity) as total_quantity from walmart
group by payment_method

/*PROJECT Q2 Identify the highest rated category in each branch,displaying branch and category avg rating*/ 
select branch,category,avg_rating FROM (
select branch,category,avg(rating) as avg_rating,RANK()OVER(PARTITION BY branch ORDER BY avg(rating) DESC)
as rnk from walmart group by branch,category)as new_table where rnk=1
/*PROJECT Q3: FIND THE BUSIEST DAY FOR EACH BRANCH BASED ON NO OF INVOICES*/
SELECT * FROM( select branch ,  
    DAYNAME(STR_TO_DATE(date, '%d/%m/%y')) AS day_name,count(invoice_id) as no_transaction,RANK() OVER(PARTITION BY branch order by COUNT(*) desc)as rnk 
    from walmart group by branch,day_name)as new_t where rnk=1
    
 /*Project Q4:For each city and each category, find minimum , maximum and average rating */
 select  city, category,MIN(rating),MAX(rating),avg(rating) from walmart
 group by city,category
 order by city asc

/*Project Q5:Calculate total profit for each category.Rank from highest profit to lowest profit.Profit=unit_price
quantity*profit_margin */
select category,SUM(total) as total_revenue, SUM(total*profit_margin) as profit
from walmart
group by category
order by profit desc

/*PROJECT Q6:For each branch find the most preferred  payment method.Return branch number in ascending order.*/
select branch,payment_method,total_count from(
select branch,payment_method,count(invoice_id) as total_count,RANK() OVER(PARTITION BY branch 
order by count(invoice_id) desc)as rnk from walmart
group by branch,payment_method
order by branch asc)as new_table
where rnk=1

/*PROJECT Q7:CATEGORIZE EACH SHIFT INTO MORNING AFTERNOON AND EVENING */
SELECT branch,
    CASE WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) < 12 THEN 'Morning'
        WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) >= 12 AND HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) <= 17 THEN 'Afternoon'
        ELSE 'Evening' 
    END AS time_of_day,
    COUNT(invoice_id) AS count_invoices 
FROM walmart
GROUP BY branch,time_of_day
order by branch,count_invoices desc

/*PROJECT Q8: IDENTIFY TOP5 BRANCHES WITH HEIGHEST DECREASE IN REVENUE(YOY RATIO) IN 2023 AS COMPARED TO 2022*/
WITH YearlyRevenue AS (
   
    SELECT 
        branch,
        YEAR(STR_TO_DATE(TRIM(date), '%d/%m/%Y')) AS fiscal_year, 
        SUM(unit_price * quantity) AS total_revenue
    FROM walmart
    GROUP BY branch, fiscal_year
)

SELECT 
    lr.branch,
    ROUND(lr.total_revenue, 2) AS rev_2022,
    ROUND(cr.total_revenue, 2) AS rev_2023,
    ROUND((lr.total_revenue - cr.total_revenue)*100/lr.total_revenue, 2) AS revenue_drop
FROM YearlyRevenue AS lr
INNER JOIN YearlyRevenue AS cr 
    ON lr.branch = cr.branch
WHERE lr.fiscal_year = 2022 
  AND cr.fiscal_year = 2023
  AND lr.total_revenue > cr.total_revenue -- Tracks where revenue dropped year-over-year
ORDER BY revenue_drop DESC
LIMIT 5;
/* Q9:FIND peak sale period based on revenue generated by taking interval of 2 hours/*/

SELECT 
    CASE 
        WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) BETWEEN 7 AND 8   THEN '07:00 - 09:00'
        WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) BETWEEN 9 AND 10  THEN '09:00 - 11:00'
        WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) BETWEEN 11 AND 12 THEN '11:00 - 13:00'
        WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) BETWEEN 13 AND 14 THEN '13:00 - 15:00'
        WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) BETWEEN 15 AND 16 THEN '15:00 - 17:00'
        WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) BETWEEN 17 AND 18 THEN '17:00 - 19:00'
        WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) BETWEEN 19 AND 20 THEN '19:00 - 21:00'
        WHEN HOUR(STR_TO_DATE(TRIM(time), '%H:%i:%s')) BETWEEN 21 AND 22 THEN '21:00 - 23:00'
        ELSE 'Other / Late Night'
    END AS time_interval,
    ROUND(SUM(unit_price * quantity), 2) AS total_revenue
FROM walmart
GROUP BY time_interval
ORDER BY total_revenue DESC;

/* Q10:FIND TOP 3 CATEGORIES BY REVENUE*/
SELECT category , sum(total) as revenue_generated
from walmart
group by category
order by sum(total) desc
limit 3
